

export const gridData = [
    {
        url : 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        title: 'Write Building Plans',
        description : 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis ipsa minima itaque fugiat nobis, vel assumenda eligendi incidunt mollitia vero quas accusantium quaerat temporibus eius aspernatur dolorem dolore natus sequi tempora saepe magnam non maiores! Harum, placeat soluta? Eos, laboriosam saepe repellat dolore nobis voluptatem delectus recusandae porro consequatur reiciendis perspiciatis corrupti quod sint, ea est a quasi veniam, inventore velit fugit corporis culpa. Itaque, quaerat illo ad voluptatem exercitationem non aliquam cupiditate hic nemo, quam libero velit at distinctio temporibus aperiam est, nisi aspernatur in quisquam maxime dolor. Esse, perferendis, aspernatur nobis enim cum ad aperiam est eum illo dolor aliquam fugit corporis, dignissimos reiciendis obcaecati consequuntur pariatur autem! Architecto dolorum vel minima quas ex, magnam ratione non perferendis neque cumque sit fugit tempore quia omnis doloremque, maxime, suscipit ducimus debitis est! Quasi voluptas ex reiciendis dignissimos, vitae nesciunt sed quas qui placeat rem veritatis minima labore obcaecati soluta asperiores iusto possimus beatae enim dolore sunt consequuntur. Magni harum aperiam laborum necessitatibus omnis officia sapiente unde. Cupiditate, voluptatum officia ab voluptas, laboriosam perspiciatis possimus vitae dolor ipsum doloribus, et quaerat voluptatem inventore sit aliquid magnam quas quod ipsa repudiandae odio saepe a doloremque? Cum impedit ipsam repudiandae! Sapiente eveniet et consectetur sit eaque hic, vel aut doloribus corporis sunt impedit magni quibusdam vero! Eos esse possimus quas suscipit quasi repellendus odio asperiores, facere modi consequuntur voluptatibus optio assumenda harum mollitia iste eligendi eum sapiente aliquam ut iusto tempore soluta reprehenderit. Corrupti nostrum delectus quas quidem ipsum fugit officia esse enim necessitatibus iusto eius totam hic cum, eos rem atque, ipsam dolor cumque repellendus ratione pariatur libero! Ratione quam enim autem aliquam. Modi sed accusantium placeat, pariatur exercitationem iste. Minus architecto, quos, doloremque sit, nam possimus in nobis eaque quae saepe quia eius sed debitis libero? Aliquam necessitatibus obcaecati odit!'
    },
    {
        url : 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475',
        title: 'Building Construction',
        description : 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis ipsa minima itaque fugiat nobis, vel assumenda eligendi incidunt mollitia vero quas accusantium quaerat temporibus eius aspernatur dolorem dolore natus sequi tempora saepe magnam non maiores! Harum, placeat soluta? Eos, laboriosam saepe repellat dolore nobis voluptatem delectus recusandae porro consequatur reiciendis perspiciatis corrupti quod sint, ea est a quasi veniam, inventore velit fugit corporis culpa. Itaque, quaerat illo ad voluptatem exercitationem non aliquam cupiditate hic nemo, quam libero velit at distinctio temporibus aperiam est, nisi aspernatur in quisquam maxime dolor. Esse, perferendis, aspernatur nobis enim cum ad aperiam est eum illo dolor aliquam fugit corporis, dignissimos reiciendis obcaecati consequuntur pariatur autem! Architecto dolorum vel minima quas ex, magnam ratione non perferendis neque cumque sit fugit tempore quia omnis doloremque, maxime, suscipit ducimus debitis est! Quasi voluptas ex reiciendis dignissimos, vitae nesciunt sed quas qui placeat rem veritatis minima labore obcaecati soluta asperiores iusto possimus beatae enim dolore sunt consequuntur. Magni harum aperiam laborum necessitatibus omnis officia sapiente unde. Cupiditate, voluptatum officia ab voluptas, laboriosam perspiciatis possimus vitae dolor ipsum doloribus, et quaerat voluptatem inventore sit aliquid magnam quas quod ipsa repudiandae odio saepe a doloremque? Cum impedit ipsam repudiandae! Sapiente eveniet et consectetur sit eaque hic, vel aut doloribus corporis sunt impedit magni quibusdam vero! Eos esse possimus quas suscipit quasi repellendus odio asperiores, facere modi consequuntur voluptatibus optio assumenda harum mollitia iste eligendi eum sapiente aliquam ut iusto tempore soluta reprehenderit. Corrupti nostrum delectus quas quidem ipsum fugit officia esse enim necessitatibus iusto eius totam hic cum, eos rem atque, ipsam dolor cumque repellendus ratione pariatur libero! Ratione quam enim autem aliquam. Modi sed accusantium placeat, pariatur exercitationem iste. Minus architecto, quos, doloremque sit, nam possimus in nobis eaque quae saepe quia eius sed debitis libero? Aliquam necessitatibus obcaecati odit!'
    },
    {
        url : 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475',
        title: 'Real Estate',
        description : 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis ipsa minima itaque fugiat nobis, vel assumenda eligendi incidunt mollitia vero quas accusantium quaerat temporibus eius aspernatur dolorem dolore natus sequi tempora saepe magnam non maiores! Harum, placeat soluta? Eos, laboriosam saepe repellat dolore nobis voluptatem delectus recusandae porro consequatur reiciendis perspiciatis corrupti quod sint, ea est a quasi veniam, inventore velit fugit corporis culpa. Itaque, quaerat illo ad voluptatem exercitationem non aliquam cupiditate hic nemo, quam libero velit at distinctio temporibus aperiam est, nisi aspernatur in quisquam maxime dolor. Esse, perferendis, aspernatur nobis enim cum ad aperiam est eum illo dolor aliquam fugit corporis, dignissimos reiciendis obcaecati consequuntur pariatur autem! Architecto dolorum vel minima quas ex, magnam ratione non perferendis neque cumque sit fugit tempore quia omnis doloremque, maxime, suscipit ducimus debitis est! Quasi voluptas ex reiciendis dignissimos, vitae nesciunt sed quas qui placeat rem veritatis minima labore obcaecati soluta asperiores iusto possimus beatae enim dolore sunt consequuntur. Magni harum aperiam laborum necessitatibus omnis officia sapiente unde. Cupiditate, voluptatum officia ab voluptas, laboriosam perspiciatis possimus vitae dolor ipsum doloribus, et quaerat voluptatem inventore sit aliquid magnam quas quod ipsa repudiandae odio saepe a doloremque? Cum impedit ipsam repudiandae! Sapiente eveniet et consectetur sit eaque hic, vel aut doloribus corporis sunt impedit magni quibusdam vero! Eos esse possimus quas suscipit quasi repellendus odio asperiores, facere modi consequuntur voluptatibus optio assumenda harum mollitia iste eligendi eum sapiente aliquam ut iusto tempore soluta reprehenderit. Corrupti nostrum delectus quas quidem ipsum fugit officia esse enim necessitatibus iusto eius totam hic cum, eos rem atque, ipsam dolor cumque repellendus ratione pariatur libero! Ratione quam enim autem aliquam. Modi sed accusantium placeat, pariatur exercitationem iste. Minus architecto, quos, doloremque sit, nam possimus in nobis eaque quae saepe quia eius sed debitis libero? Aliquam necessitatibus obcaecati odit!'
    },
    {
        url : 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147',
        title: 'Liocam Online Store',
        description : 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis ipsa minima itaque fugiat nobis, vel assumenda eligendi incidunt mollitia vero quas accusantium quaerat temporibus eius aspernatur dolorem dolore natus sequi tempora saepe magnam non maiores! Harum, placeat soluta? Eos, laboriosam saepe repellat dolore nobis voluptatem delectus recusandae porro consequatur reiciendis perspiciatis corrupti quod sint, ea est a quasi veniam, inventore velit fugit corporis culpa. Itaque, quaerat illo ad voluptatem exercitationem non aliquam cupiditate hic nemo, quam libero velit at distinctio temporibus aperiam est, nisi aspernatur in quisquam maxime dolor. Esse, perferendis, aspernatur nobis enim cum ad aperiam est eum illo dolor aliquam fugit corporis, dignissimos reiciendis obcaecati consequuntur pariatur autem! Architecto dolorum vel minima quas ex, magnam ratione non perferendis neque cumque sit fugit tempore quia omnis doloremque, maxime, suscipit ducimus debitis est! Quasi voluptas ex reiciendis dignissimos, vitae nesciunt sed quas qui placeat rem veritatis minima labore obcaecati soluta asperiores iusto possimus beatae enim dolore sunt consequuntur. Magni harum aperiam laborum necessitatibus omnis officia sapiente unde. Cupiditate, voluptatum officia ab voluptas, laboriosam perspiciatis possimus vitae dolor ipsum doloribus, et quaerat voluptatem inventore sit aliquid magnam quas quod ipsa repudiandae odio saepe a doloremque? Cum impedit ipsam repudiandae! Sapiente eveniet et consectetur sit eaque hic, vel aut doloribus corporis sunt impedit magni quibusdam vero! Eos esse possimus quas suscipit quasi repellendus odio asperiores, facere modi consequuntur voluptatibus optio assumenda harum mollitia iste eligendi eum sapiente aliquam ut iusto tempore soluta reprehenderit. Corrupti nostrum delectus quas quidem ipsum fugit officia esse enim necessitatibus iusto eius totam hic cum, eos rem atque, ipsam dolor cumque repellendus ratione pariatur libero! Ratione quam enim autem aliquam. Modi sed accusantium placeat, pariatur exercitationem iste. Minus architecto, quos, doloremque sit, nam possimus in nobis eaque quae saepe quia eius sed debitis libero? Aliquam necessitatibus obcaecati odit!'
    }
]

export const projects = [
    {
        date : '10/10/2021',
        _id: 0,
        id : 1,
        images : ['https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'bungalow',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 1,
        id : 2,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'bungalow',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 2,
        id : 3,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'bungalow',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 3,
        id : 4,
        images : ['https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'bungalow',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id : 4,
        id : 5,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'bungalow',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id : 5,
        id : 6,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'bungalow',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 6,
        id : 7,
        images : ['https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'duplex',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 7,
        id : 8,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'duplex',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 8,
        id : 9,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'duplex',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 9,
        id : 10,
        images : ['https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'duplex',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id : 10,
        id : 11,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'duplex',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id : 11,
        id : 12,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'duplex',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 12,
        id : 13,
        images : ['https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'apartment',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 13,
        id : 14,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'apartment',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 14,
        id : 15,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'apartment',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 15,
        id : 16,
        images : ['https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'apartment',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id : 16,
        id : 17,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'apartment',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id : 17,
        id : 18,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'apartment',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 18,
        id : 19,
        images : ['https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'other',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 19,
        id : 20,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'other',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 20,
        id : 21,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'other',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id: 21,
        id : 22,
        images : ['https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'other',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id : 22,
        id : 23,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475', 'https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'other',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    },
    {
        date : '10/10/2021',
        _id : 23,
        id : 24,
        images : ['https://cdn.shopify.com/s/files/1/0567/3873/products/Perspective_1_8178b0d6-958d-4282-832d-8ec09f29e7a7_724x482.progressive.jpg?v=1546936147', 'https://images.pexels.com/photos/4792491/pexels-photo-4792491.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://cdn.shopify.com/s/files/1/0567/3873/products/P1_81d3f450-1b08-47f9-bbeb-8de325c6f122_724x482.progressive.jpg?v=1546936475'],
        name: 'Some item title',
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum quas, voluptates maiores hic voluptatem aliquid deleniti adipisci, alias atque mollitia, tempore quisquam inventore nam? Beatae voluptatum accusantium maxime cum quae molestiae tempora rem sequi, quam quia quaerat est consequuntur repudiandae ipsa ipsam non accusamus vero nisi illum iure incidunt obcaecati.',
        category : 'other',
        plotWidth : "20 sq m",
        plotLength : '20 sq m',
        parking : 'no parking',
        plotArea : '400 sq m',
        freeSpace : '100 sq m',
        stories : '1',
        apartments : '5',
        livingRooms : '5',
        rooms: '20',
        toilets : '10',
        kitchens : '5',
        balconies : '10',
        verandas : '10',
        drawingList : [
            {
                name : 'floor plan',
                format : 'pdf/img',
            },
            {
                name : 'house plan',
                format : 'pdf/img',
            },
            {
                name : 'elevation plan',
                format : 'pdf/img',
            }
        ],
        basicPrice : 'XAF 500000',
        standardPrice : 'XAF 700000',
        premiumPrice : 'XAF 1000000'
    }
]

export const products = [
    {
        _id : 0,
        id : 1,
        price : 10000,
        name : 'Some product name',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel beatae obcaecati perspiciatis sapiente voluptate ipsum inventore illum magni. Tempore quaerat officiis provident autem et commodi debitis laboriosam est vitae ea amet necessitatibus, enim quia repellendus facilis accusamus cum in error placeat tenetur blanditiis nihil deleniti quisquam totam. Quae, asperiores doloribus.',
        images : ['https://images.pexels.com/photos/5570224/pexels-photo-5570224.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://media.istockphoto.com/photos/looking-for-the-right-angle-picture-id168356310?b=1&k=20&m=168356310&s=170667a&w=0&h=5IgvqW4V3PFWgMUiFZ2lQOot_L9IRqg9jicbgOQ9Kz0=', 'https://images.unsplash.com/photo-1627882206813-8c1ffd86efec?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8YnVpbGRpbmclMjBtYXRlcmlhbHN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60', 'https://media.istockphoto.com/photos/lumber-picture-id473849692?b=1&k=20&m=473849692&s=170667a&w=0&h=xKFToHoIpF4zGvWqErK2xBeZCDsIYau2NaPyZmwpLk0=']
    },
    {
        _id : 1,
        id : 2,
        price : 20000,
        name : 'Some product name',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel beatae obcaecati perspiciatis sapiente voluptate ipsum inventore illum magni. Tempore quaerat officiis provident autem et commodi debitis laboriosam est vitae ea amet necessitatibus, enim quia repellendus facilis accusamus cum in error placeat tenetur blanditiis nihil deleniti quisquam totam. Quae, asperiores doloribus.',
        images : ['https://media.istockphoto.com/photos/lumber-picture-id473849692?b=1&k=20&m=473849692&s=170667a&w=0&h=xKFToHoIpF4zGvWqErK2xBeZCDsIYau2NaPyZmwpLk0=','https://images.pexels.com/photos/5570224/pexels-photo-5570224.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://media.istockphoto.com/photos/looking-for-the-right-angle-picture-id168356310?b=1&k=20&m=168356310&s=170667a&w=0&h=5IgvqW4V3PFWgMUiFZ2lQOot_L9IRqg9jicbgOQ9Kz0=', 'https://images.unsplash.com/photo-1627882206813-8c1ffd86efec?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8YnVpbGRpbmclMjBtYXRlcmlhbHN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60']
    },
    {
        _id : 2,
        id : 3,
        price : 30000,
        name : 'Some product name',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel beatae obcaecati perspiciatis sapiente voluptate ipsum inventore illum magni. Tempore quaerat officiis provident autem et commodi debitis laboriosam est vitae ea amet necessitatibus, enim quia repellendus facilis accusamus cum in error placeat tenetur blanditiis nihil deleniti quisquam totam. Quae, asperiores doloribus.',
        images : ['https://images.unsplash.com/photo-1627882206813-8c1ffd86efec?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8YnVpbGRpbmclMjBtYXRlcmlhbHN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60','https://media.istockphoto.com/photos/lumber-picture-id473849692?b=1&k=20&m=473849692&s=170667a&w=0&h=xKFToHoIpF4zGvWqErK2xBeZCDsIYau2NaPyZmwpLk0=','https://images.pexels.com/photos/5570224/pexels-photo-5570224.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://media.istockphoto.com/photos/looking-for-the-right-angle-picture-id168356310?b=1&k=20&m=168356310&s=170667a&w=0&h=5IgvqW4V3PFWgMUiFZ2lQOot_L9IRqg9jicbgOQ9Kz0=']
    },
    {
        _id : 3,
        id : 4,
        price : 40000,
        name : 'Some product name',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel beatae obcaecati perspiciatis sapiente voluptate ipsum inventore illum magni. Tempore quaerat officiis provident autem et commodi debitis laboriosam est vitae ea amet necessitatibus, enim quia repellendus facilis accusamus cum in error placeat tenetur blanditiis nihil deleniti quisquam totam. Quae, asperiores doloribus.',
        images : ['https://media.istockphoto.com/photos/looking-for-the-right-angle-picture-id168356310?b=1&k=20&m=168356310&s=170667a&w=0&h=5IgvqW4V3PFWgMUiFZ2lQOot_L9IRqg9jicbgOQ9Kz0=','https://images.unsplash.com/photo-1627882206813-8c1ffd86efec?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8YnVpbGRpbmclMjBtYXRlcmlhbHN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60','https://media.istockphoto.com/photos/lumber-picture-id473849692?b=1&k=20&m=473849692&s=170667a&w=0&h=xKFToHoIpF4zGvWqErK2xBeZCDsIYau2NaPyZmwpLk0=','https://images.pexels.com/photos/5570224/pexels-photo-5570224.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500']
    },
    {
        _id : 4,
        id : 5,
        price : 50000,
        name : 'Some product name',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel beatae obcaecati perspiciatis sapiente voluptate ipsum inventore illum magni. Tempore quaerat officiis provident autem et commodi debitis laboriosam est vitae ea amet necessitatibus, enim quia repellendus facilis accusamus cum in error placeat tenetur blanditiis nihil deleniti quisquam totam. Quae, asperiores doloribus.',
        images : ['https://images.pexels.com/photos/5570224/pexels-photo-5570224.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500','https://media.istockphoto.com/photos/looking-for-the-right-angle-picture-id168356310?b=1&k=20&m=168356310&s=170667a&w=0&h=5IgvqW4V3PFWgMUiFZ2lQOot_L9IRqg9jicbgOQ9Kz0=','https://images.unsplash.com/photo-1627882206813-8c1ffd86efec?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8YnVpbGRpbmclMjBtYXRlcmlhbHN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60','https://media.istockphoto.com/photos/lumber-picture-id473849692?b=1&k=20&m=473849692&s=170667a&w=0&h=xKFToHoIpF4zGvWqErK2xBeZCDsIYau2NaPyZmwpLk0=']
    },
    {
        _id : 5,
        id : 6,
        price : 60000,
        name : 'Some product name',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel beatae obcaecati perspiciatis sapiente voluptate ipsum inventore illum magni. Tempore quaerat officiis provident autem et commodi debitis laboriosam est vitae ea amet necessitatibus, enim quia repellendus facilis accusamus cum in error placeat tenetur blanditiis nihil deleniti quisquam totam. Quae, asperiores doloribus.',
        images : ['https://media.istockphoto.com/photos/lumber-picture-id473849692?b=1&k=20&m=473849692&s=170667a&w=0&h=xKFToHoIpF4zGvWqErK2xBeZCDsIYau2NaPyZmwpLk0=','https://images.pexels.com/photos/5570224/pexels-photo-5570224.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500','https://media.istockphoto.com/photos/looking-for-the-right-angle-picture-id168356310?b=1&k=20&m=168356310&s=170667a&w=0&h=5IgvqW4V3PFWgMUiFZ2lQOot_L9IRqg9jicbgOQ9Kz0=','https://images.unsplash.com/photo-1627882206813-8c1ffd86efec?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8YnVpbGRpbmclMjBtYXRlcmlhbHN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60']
    },
]